name: Continuous Integration

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - name: Install dependencies
        run: npm install
      - name: Run static analysis
        run: npm run test:static
      - name: Run unit tests
        run: npm run test:unit
      - name: Build the project
        run: npm run build
      - name: Package the lambda
        run: npm run package
